### ISSUE TITLE
Tag and publish all plugins

### ISSUE THREAD

**Issue by bautisflow** [thinger-io/plugins#6]
- [x] Add DockerHub's credentials @alvarolb 
- [x] Commit and upload all plugins @bautisflow 
- [x] Decision on how to handle available versions in Thinger.io Plugin Marketplace (¿.version file or tags?)

**Comment by bautisflow** [comment]
A .version file would give us full control of versions and autonomy over previously used git tags, so any time we want to add or remove a new version we would modify this file in the plugin’s subdirectory of the repository. The file is called `.version.yaml` and has the following structure:

```yaml
---
releases:
  latest:
    - 1.4.0
  development:
    - main
    - develop
  deprecated: null
```
